#include <stdio.h>
#include <glibconfig.h>

int main(void)
{
  printf("# This part is generated by generate-constants.c\n");
  printf("G_MINFLOAT = %f\n", G_MINFLOAT);
  printf("G_MINFLOAT = %f\n", G_MINFLOAT);
  printf("G_MAXFLOAT = %f\n", G_MAXFLOAT);
  printf("G_MINDOUBLE = %f\n", G_MINDOUBLE);
  printf("G_MAXDOUBLE = %f\n", G_MAXDOUBLE);
  printf("G_MINSHORT = %d\n", G_MINSHORT);
  printf("G_MAXSHORT = %d\n", G_MAXSHORT);
  printf("G_MAXUSHORT = %u\n", G_MAXUSHORT);
  printf("G_MININT = %d\n", G_MININT);
  printf("G_MAXINT = %d\n", G_MAXINT);
  printf("G_MAXUINT = %u\n", G_MAXUINT);
  printf("G_MINLONG = %ldL\n", G_MINLONG);
  printf("G_MAXLONG = %ldL\n", G_MAXLONG);
  printf("G_MAXULONG = %luL\n", G_MAXULONG);
}
