# This is a configuration file for the pre-commit tool.
# Documentation is available at https://pre-commit.com/#plugins

repos:
- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.10.0.1
  hooks:
  - id: shellcheck
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: 'v0.12.4'
  hooks:
    - id: ruff
      args: [--fix, --preview]
    - id: ruff-format
      types_or: [python, spec]
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    - id: trailing-whitespace
    - id: check-toml
    - id: check-yaml
      args: [--allow-multiple-documents]
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v20.1.8
  hooks:
    - id: clang-format
